- name: Install OpenShift client
  shell: |
    curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz | tar zxvf - -C /usr/local/bin
  args:
    creates: /usr/local/bin/oc
  become: yes

- name: Install OpenShift installer
  shell: |
    curl -s https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-install-linux.tar.gz | tar zxvf - -C /usr/local/bin
  args:
    creates: /usr/local/bin/openshift-install
  become: yes
