# rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: example-rolebinding
  namespace: alyaabadr
subjects:
- kind: ServiceAccount
  name: example-serviceaccount
  namespace: alyaabadr
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io


