---
# roles/jenkins/meta/main.yml

galaxy_info:
  author: ALyaa Badr
  description: Install and configure Jenkins
  company: ivolve
  license: MIT
  min_ansible_version: 2.9

  platforms:
    - name: Debian
      versions:
        - buster
        - bullseye

    - name: Ubuntu
      versions:
        - focal
        - bionic

dependencies: []

