- name: Update apt package list
      apt:
        update_cache: yes
- name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present

- name: Add Jenkins repository key
      apt_key:
        url: https://pkg.jenkins.io/debian/jenkins.io.key
        state: present

- name: Add Jenkins repository
      apt_repository:
        repo: deb http://pkg.jenkins.io/debian-stable binary/
        state: present

- name: Update apt package list after adding Jenkins repository
      apt:
        update_cache: yes

- name: Install Jenkins
      apt:
        name: jenkins
        state: present

- name: Ensure Jenkins is started and enabled
      systemd:
        name: jenkins
        enabled: yes
        state: started
   
